spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playlist?serverTimezone=Asia/Seoul
    username: root
    password: 5679

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  profile:
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug